import { NextResponse } from "next/server";
import { getLLM } from "@/lib/ai-provider";
import { createClient } from "@supabase/supabase-js";
import { HumanMessage, SystemMessage } from "@langchain/core/messages";
import { StateGraph, START, END } from "@langchain/langgraph";
import { RunnableConfig } from "@langchain/core/runnables";

const supabase = createClient(
  process.env.SUPABASE_URL || "",
  process.env.SUPABASE_KEY || ""
);

// Define the State
interface DraftState {
  projectId: string;
  context: string;
  abstract: string;
  introduction: string;
  literatureReview: string;
  methodology: string;
  results: string;
  conclusion: string;
  finalDraft: string;
}

let globalReq: Request;
const getModel = () => {
  return getLLM(globalReq, 0.7, "gemini-1.5-pro");
};

async function fetchContext(state: DraftState): Promise<Partial<DraftState>> {
  const { data: claimsData } = await supabase
    .from("Documents")
    .select("content")
    .eq("metadata->>project_id", state.projectId)
    .eq("metadata->>type", "verified_claim");

  const claims = claimsData?.map(c => JSON.parse(c.content)) || [];

  const { data: insights } = await supabase
    .from("Insights")
    .select("title, description, type")
    .eq("project_id", state.projectId);

  let contextBuilder = "=== PROJECT CONTEXT ===\n\n";
  if (insights) {
    contextBuilder += "RESEARCH FOCUS / HYPOTHESES:\n";
    insights.forEach((i: any) => contextBuilder += `- ${i.title}: ${i.description}\n`);
  }
  if (claims) {
    contextBuilder += "\nVERIFIED CLAIMS / RESULTS:\n";
    claims.forEach((c: any) => contextBuilder += `- [${c.ai_verdict}] ${c.claim_text}\n`);
  }

  return { context: contextBuilder };
}

async function draftAbstract(state: DraftState): Promise<Partial<DraftState>> {
  const model = getModel();
  const prompt = `You are an expert academic researcher. Based on the following project context, draft a concise and compelling Abstract (max 250 words) for a research paper.\n\nContext:\n${state.context}`;
  const response = await model.invoke([new SystemMessage(prompt)]);
  return { abstract: `<h2>Abstract</h2>\n<p>${response.content}</p>` };
}

async function draftIntroduction(state: DraftState): Promise<Partial<DraftState>> {
  const model = getModel();
  const prompt = `You are an expert academic researcher. Draft the Introduction section for a research paper based on the project context. Establish the problem, context, and outline the paper's contribution.\n\nContext:\n${state.context}`;
  const response = await model.invoke([new SystemMessage(prompt)]);
  return { introduction: `<h2>1. Introduction</h2>\n<p>${response.content}</p>` };
}

async function draftLiteratureReview(state: DraftState): Promise<Partial<DraftState>> {
  const model = getModel();
  const prompt = `You are an expert academic researcher. Draft a brief Literature Review section summarizing the theoretical background based on the hypotheses/context provided. Cite creatively if specific literature is missing.\n\nContext:\n${state.context}`;
  const response = await model.invoke([new SystemMessage(prompt)]);
  return { literatureReview: `<h2>2. Literature Review</h2>\n<p>${response.content}</p>` };
}

async function draftMethodology(state: DraftState): Promise<Partial<DraftState>> {
  const model = getModel();
  const prompt = `You are an expert academic researcher. Draft the Methodology section outlining the research design implied by the context.\n\nContext:\n${state.context}`;
  const response = await model.invoke([new SystemMessage(prompt)]);
  return { methodology: `<h2>3. Methodology</h2>\n<p>${response.content}</p>` };
}

async function draftResults(state: DraftState): Promise<Partial<DraftState>> {
  const model = getModel();
  const prompt = `You are an expert academic researcher. Draft the Results & Discussion section. Heavily rely on the VERIFIED CLAIMS provided in the context.\n\nContext:\n${state.context}`;
  const response = await model.invoke([new SystemMessage(prompt)]);
  return { results: `<h2>4. Results and Discussion</h2>\n<p>${response.content}</p>` };
}

async function draftConclusion(state: DraftState): Promise<Partial<DraftState>> {
  const model = getModel();
  const prompt = `You are an expert academic researcher. Draft a concise Conclusion section summarizing the findings and suggesting future work.\n\nContext:\n${state.context}`;
  const response = await model.invoke([new SystemMessage(prompt)]);
  return { conclusion: `<h2>5. Conclusion</h2>\n<p>${response.content}</p>` };
}

function compileDraft(state: DraftState): Partial<DraftState> {
  const finalDraft = `
    <h1 style="text-align: center;">Draft Research Paper</h1>
    <p style="text-align: center;"><em>Generated by Plotoris AI Team</em></p>
    ${state.abstract || ""}
    ${state.introduction || ""}
    ${state.literatureReview || ""}
    ${state.methodology || ""}
    ${state.results || ""}
    ${state.conclusion || ""}
  `;
  return { finalDraft };
}

export async function POST(request: Request) {
  globalReq = request;
  try {
    const { projectId } = await request.json();
    if (!projectId) return NextResponse.json({ error: "Missing projectId" }, { status: 400 });

    const stateChannels = {
      projectId: null,
      context: null,
      abstract: null,
      introduction: null,
      literatureReview: null,
      methodology: null,
      results: null,
      conclusion: null,
      finalDraft: null,
    };

    const graphBuilder = new StateGraph<DraftState>({ channels: stateChannels as any })
      .addNode("fetchContext", fetchContext)
      .addNode("draftAbstract", draftAbstract)
      .addNode("draftIntroduction", draftIntroduction)
      .addNode("draftLiteratureReview", draftLiteratureReview)
      .addNode("draftMethodology", draftMethodology)
      .addNode("draftResults", draftResults)
      .addNode("draftConclusion", draftConclusion)
      .addNode("compile", compileDraft)

      .addEdge(START, "fetchContext")
      .addEdge("fetchContext", "draftAbstract")
      .addEdge("fetchContext", "draftIntroduction")
      .addEdge("fetchContext", "draftLiteratureReview")
      .addEdge("fetchContext", "draftMethodology")
      .addEdge("fetchContext", "draftResults")
      .addEdge("fetchContext", "draftConclusion")
      .addEdge("draftAbstract", "compile")
      .addEdge("draftIntroduction", "compile")
      .addEdge("draftLiteratureReview", "compile")
      .addEdge("draftMethodology", "compile")
      .addEdge("draftResults", "compile")
      .addEdge("draftConclusion", "compile")
      .addEdge("compile", END);

    const graph = graphBuilder.compile();

    const initialState: Partial<DraftState> = { projectId };
    
    // Run the graph
    const result = await graph.invoke(initialState, { recursionLimit: 10 });

    return NextResponse.json({ draft: result.finalDraft });
  } catch (err) {
    console.error("Drafting error:", err);
    return NextResponse.json({ error: "Internal server error" }, { status: 500 });
  }
}
